Style/FrozenStringLiteralComment:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/Documentation:
    Enabled: false

Metrics/BlockLength:
    Exclude:
        - spec/**/*

Style/HashSyntax:
    EnforcedShorthandSyntax: either

AllCops:
    Exclude:
        - 'db/schema.rb'
